<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>Calculadora PHP</title>
</head>
<body>
<div class="container vh-100 text-center">
        <h1>Calculadora Simple</h1>
        <div class="row align-items-start">
            <div class="col">
                
            </div>
            <div class="col">
                <form method="POST">
                    <input style="padding: 3px; margin: 0; min-height: 20px;" value="<?php echo getInputAsString($input);?>">
                    <input class="form-control" type="hidden" name="input" value='<?php echo json_encode($input);?>'/>
                    <table>
                        <tr>
                            <td><input class="form-control" type="submit" name="c" value="C"/></td>
                        </tr>
                    </table>
                </form>
            </div>
            <div class="col">
            
            </div>
        </div>
        </div>
</body>
</html>